version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stack-pooled"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ryn15akqjfyk"
s3_prefix = "stack-pooled"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "TenantIdParameter=\"pooled\" CognitoUserPoolIdParameter=\"us-east-1_vYiTK6qHu\" CognitoAppClientIdParameter=\"cie02pu47amai54g1g1lsc5kl\" StageName=\"prod\" BootstrapStackName=\"serverless-saas\" LambdaReserveConcurrency=\"20\" LambdaCanaryDeploymentPreference=\"True\""
image_repositories = []
